Repository UpendoVentures/Upendo-Dnn-Prompt, pull requests merged in 2025-04, with the labels that each got.

#75 Turn off admin message setting
  Modules/UpendoPrompt/App_LocalResources/Global.resx
  Modules/UpendoPrompt/Commands/DisableAdminMessage.cs
  Modules/UpendoPrompt/Components/Constants.cs
  Modules/UpendoPrompt/Upendo.Modules.UpendoPrompt.csproj
Labels: enhancement

#77 Tasks/issue 76
  Modules/UpendoPrompt/Properties/AssemblyInfo.cs
  Modules/UpendoPrompt/UpendoPrompt.dnn
  Modules/UpendoPrompt/UpendoPrompt_Symbols.dnn
  Modules/UpendoPrompt/releasenotes.txt
Labels: task

#78 Update Global.resx
  Modules/UpendoPrompt/App_LocalResources/Global.resx
Labels: bug

#80 Issues/issue 79
  Modules/UpendoPrompt/Properties/AssemblyInfo.cs
  Modules/UpendoPrompt/UpendoPrompt.dnn
  Modules/UpendoPrompt/UpendoPrompt_Symbols.dnn
  Modules/UpendoPrompt/releasenotes.txt
Labels: task
