Repository UpendoVentures/Upendo-Dnn-Prompt, pull requests merged in 2025-03, with the labels that each got.

#70 Add -scheduler Option to compress-log-files Command for Scheduled Job Management
  Modules/UpendoPrompt/App_LocalResources/Global.resx
  Modules/UpendoPrompt/Commands/CompressLogFiles.cs
  Modules/UpendoPrompt/Components/Constants.cs
  Modules/UpendoPrompt/UpendoPrompt.dnn
Labels: bug, enhancement

#72 Add sponsor messaging
  Modules/UpendoPrompt/App_LocalResources/Global.resx
  Modules/UpendoPrompt/Commands/ApplyRoles.cs
  Modules/UpendoPrompt/Commands/CaptchaMode.cs
  Modules/UpendoPrompt/Commands/CompressLogFiles.cs
  Modules/UpendoPrompt/Commands/DebugInfo.cs
  Modules/UpendoPrompt/Commands/DebugMode.cs
  Modules/UpendoPrompt/Commands/DeleteDemoUsers.cs
  Modules/UpendoPrompt/Commands/DeletePackages .cs
  Modules/UpendoPrompt/Commands/DeleteTempFolder.cs
  Modules/UpendoPrompt/Commands/DeleteTestUsers.cs
  Modules/UpendoPrompt/Commands/DemoUsers.cs
  Modules/UpendoPrompt/Commands/Deprecated/DebugInfo.cs
  Modules/UpendoPrompt/Commands/Deprecated/DebugMode.cs
  Modules/UpendoPrompt/Commands/Deprecated/PopupMode.cs
  Modules/UpendoPrompt/Commands/Deprecated/ThemesUsed.cs
  Modules/UpendoPrompt/Commands/Impersonate.cs
  Modules/UpendoPrompt/Commands/ListAvailablePackages.cs
  Modules/UpendoPrompt/Commands/ListPackages.cs
  Modules/UpendoPrompt/Commands/PopupMode.cs
  Modules/UpendoPrompt/Commands/ResetPassword.cs
  Modules/UpendoPrompt/Commands/TestUsers.cs
  Modules/UpendoPrompt/Commands/ThemesUsed.cs
  Modules/UpendoPrompt/Components/Constants.cs
  Modules/UpendoPrompt/Custom/CustomConsoleResultModel.cs
  Modules/UpendoPrompt/Upendo.Modules.UpendoPrompt.csproj
Labels: enhancement

#73 Issues/issue 71
  Modules/UpendoPrompt/Properties/AssemblyInfo.cs
  Modules/UpendoPrompt/UpendoPrompt.dnn
  Modules/UpendoPrompt/UpendoPrompt_Symbols.dnn
  Modules/UpendoPrompt/View.ascx
  Modules/UpendoPrompt/releasenotes.txt
Labels: task
